### ISSUE TITLE
Update newFractal 

### ISSUE THREAD

**Issue by Velua** [gofractally/psibase#340] opened 2023-03-13 22:03 UTC
## John
Find immutable params and place into `::newFractal`
Mutable params will have their own dedicated action `::setX`

**Comment by Velua** [comment] 2023-03-13 22:05
Fractal name
Fractal description
English
Code of conduct

**Comment by Velua** [comment] 2023-03-13 22:05
Time zone, meeting time, frequency, date of first meeting, meeting duration,

**Comment by James-Mart** [comment] 2023-03-14 02:18
Closing as dupe of #317

**Closed by James-Mart** 2023-03-14 02:18 UTC
